Bump csi-cloudscale to v3.1.0
projectsyn/component-csi-cloudscale pull request #22
Opened 2021-11-05 15:56 UTC by mhutter

https://github.com/cloudscale-ch/csi-cloudscale/blob/master/CHANGELOG.md#v310---20211105

Main features:

- Use quay.io instead of Docker Hub.
- Support raw block volume mode (not in conjunction with LUKS for now)

## Checklist

- [ ] Keep pull requests small so they can be easily reviewed.
- [ ] Update the documentation.
- [ ] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog
- [ ] Link this PR to related issues.

2021-11-08 08:54 UTC, glrf approved these changes

2021-11-08 08:54 UTC, glrf approved these changes

2021-11-08 09:04 UTC, simu requested changes
Please update the documentation as well. At least the default version in https://github.com/projectsyn/component-csi-cloudscale/blob/dc4586860e65a1f49d65cbf7d33b45e87be9bc3d/docs/modules/ROOT/pages/references/parameters.adoc#L21 is quite outdated.

2021-11-16 13:38 UTC, megian approved these changes

2021-11-16 13:48 UTC, simu reviewed
I don't see a reason to mark this as a breaking change, since there's no manual steps required for the upgrade and no component parameters are modified in a backwards-incompatible way.

2021-11-16 14:06 UTC, simu approved these changes

2021-11-16 14:06 UTC, simu commented on docs/modules/ROOT/pages/index.adoc
> +Not every version of the cloudscal.ch CSI driver is compatible with every Kubernetes versions.
```suggestion
Not every version of the cloudscale.ch CSI driver is compatible with every Kubernetes versions.
```

2021-11-16 14:50 UTC, merged